id: demo
name: Demo
tagline: Services needed to operate the Open Terms Archive engine
description: |
  The Demo collection, maintained by the Open Terms Archive Core Team, serves to track changes to the contractual documents of services needed to operate the Open Terms Archive engine. Tracking these documents allows Open Terms Archive to ensure a wholistic approach to reaching its objectives by verifying value alignment across the services that contribute to its implementation.

  The documents in this collection fall under European Union jurisdiction and are in English.
dataset: https://github.com/OpenTermsArchive/demo-versions/releases
declarations: https://github.com/OpenTermsArchive/demo-declarations
versions: https://github.com/OpenTermsArchive/demo-versions
snapshots: https://github.com/OpenTermsArchive/demo-snapshots
donations: https://opencollective.com/opentermsarchive
logo: https://opentermsarchive.org/images/collections/demo.png
languages: [en]
jurisdictions: [EU]
trackingPeriods:
  startDate: 2023-04-23
  schedule: "30 */12 * * *"
  serverLocation: Roubaix, FR
governance:
  hosts: 
    - name: Ministry for Europe and Foreign Affairs
      url: https://www.diplomatie.gouv.fr/en/
      logo: https://opentermsarchive.org/images/contributors/meae.png
  administrators:
    - name: Open Terms Archive
      url: https://opentermsarchive.org/
      logo: https://opentermsarchive.org/images/logo/logo-open-terms-archive-black.png
  curators:
    - name: Open Terms Archive
      url: https://opentermsarchive.org/
      logo: https://opentermsarchive.org/images/logo/logo-open-terms-archive-black.png
  maintainers:
    - name: Open Terms Archive
      url: https://opentermsarchive.org/
      logo: https://opentermsarchive.org/images/logo/logo-open-terms-archive-black.png
  sponsors: 
    - name: Ministry for Europe and Foreign Affairs
      url: https://www.diplomatie.gouv.fr/en/
      logo: https://opentermsarchive.org/images/contributors/meae.png

i18n:
  fr: 
    name: Démo
    tagline: Services nécessaires au fonctionnement du moteur Open Terms Archive
    description: | 
      La collection Demo, maintenue par l'équipe centrale de l'Open Terms Archive, sert à suivre les modifications des documents contractuels des services nécessaires au fonctionnement du moteur Open Terms Archive. Le suivi de ces documents permet à Open Terms Archive d'adopter une approche holistique pour atteindre ses objectifs, en vérifiant l'alignement des valeurs entre les services contribuant à sa mise en œuvre.

      Les documents de cette collection relèvent de la juridiction de l'Union européenne et sont rédigés en anglais.
    governance:
      hosts: 
        - name: Ministère de l'Europe et des Affaires étrangères 
          url: https://www.diplomatie.gouv.fr
          logo: https://opentermsarchive.org/images/contributors/meae.png
      sponsors: 
        - name: Ministère de l'Europe et des Affaires étrangères 
          url: https://www.diplomatie.gouv.fr
          logo: https://opentermsarchive.org/images/contributors/meae.png
